import { DataContext } from '@context/DataContext'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <DataContext>
          {children}
        </DataContext>
      </body>
    </html>
  )
}
